name: Build and Publish

on:
  push:
    branches:
      - master
      - dev

    tags:
      - '*'

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install
        run: |
          npm install -g pyright
          python -m pip install pytest pytest-asyncio
          python -m pip install --pre --index-url https://www.myget.org/F/apollo3zehn-dev/python/ nexus-remoting

      - name: Test
        run: |
          pyright
          pytest